const getArabicTeamName = (teamName: string) => {
  if (teamName === 'Qatar') return 'قطر'
  if (teamName === 'Ecuador') return 'الإكوادور'
  if (teamName === 'England') return 'إنجلترا'
  if (teamName === 'Iran') return 'إيران'
  if (teamName === 'Senegal') return 'السنغال'
  if (teamName === 'Netherlands') return 'هولندا'
  if (teamName === 'USA') return 'الولايات المتحدة'
  if (teamName === 'Wales') return 'ويلز'
  if (teamName === 'Argentina') return 'الأرجنتين'
  if (teamName === 'Saudi Arabia') return 'المملكة العربية السعودية'
  if (teamName === 'Denmark') return 'الدنمارك'
  if (teamName === 'Tunisia') return 'تونس'
  if (teamName === 'Mexico') return 'المكسيك'
  if (teamName === 'Poland') return 'بولندا'
  if (teamName === 'France') return 'فرنسا'
  if (teamName === 'Australia') return 'أستراليا'
  if (teamName === 'Morocco') return 'المغرب'
  if (teamName === 'Croatia') return 'كرواتيا'
  if (teamName === 'Germany') return 'ألمانيا'
  if (teamName === 'Japan') return 'اليابان'
  if (teamName === 'Spain') return 'إسبانيا'
  if (teamName === 'Costa Rica') return 'كوستاريكا'
  if (teamName === 'Belgium') return 'بلجيكا'
  if (teamName === 'Canada') return 'كندا'
  if (teamName === 'Switzerland') return 'سويسرا'
  if (teamName === 'Cameroon') return 'الكاميرون'
  if (teamName === 'Uruquay') return 'أوروغواي'
  if (teamName === 'Korea Republic') return 'كوريا الجنوبية'
  if (teamName === 'Portugal') return 'البرتغال'
  if (teamName === 'Ghana') return 'غانا'
  if (teamName === 'Brazil') return 'البرازيل'
  if (teamName === 'Serbia') return 'صربيا'
}

export default getArabicTeamName